#! /bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ -f ~/.ssetup ]]; then
    source ~/.ssetup
fi

(cd $SCRIPT_DIR; xrdb Xresources)

source $SCRIPT_DIR/configure_x.sh
source $SCRIPT_DIR/configure_monitors.sh
source $SCRIPT_DIR/configure_bspwm.sh
source $SCRIPT_DIR/configure_wallpapers.sh
source $SCRIPT_DIR/configure_applications.sh

source $SCRIPT_DIR/launch_sxhkd.sh
source $SCRIPT_DIR/launch_polybar.sh $internal_monitor $external_monitor 
source $SCRIPT_DIR/launch_picom.sh 
