#! /bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [[ -f ~/.ssetup ]]; then
    . ~/.ssetup
fi

(cd $SCRIPT_DIR; xrdb Xresources)

. $SCRIPT_DIR/configure_x.sh
. $SCRIPT_DIR/configure_monitors.sh
. $SCRIPT_DIR/configure_bspwm.sh
. $SCRIPT_DIR/configure_wallpapers.sh
. $SCRIPT_DIR/configure_applications.sh

. $SCRIPT_DIR/launch_sxhkd.sh
. $SCRIPT_DIR/launch_polybar.sh $internal_monitor $external_monitor 
. $SCRIPT_DIR/launch_picom.sh 
