#! /bin/bash

# Use command "xprop | grep WM_CLASS" to find the name of the application to be entered below
# After the command click on the application window and the name will be generated after the command and use the name generated by this command.
bspc rule -a Brave-browser      desktop='^1'    follow=on
bspc rule -a Gimp               desktop='^8'    follow=on
bspc rule -a wine               desktop='^7'    follow=on state=floating
bspc rule -a variety                            state=floating
bspc rule -a Chromium           desktop='^2'
bspc rule -a mplayer2                           state=floating
bspc rule -a Kupfer.py                          focus=on
bspc rule -a Screenkey                          manage=off
bspc rule -a discord            desktop='^4'
bspc rule -a firefox            desktop='^3'
bspc rule -a TelegramDesktop    desktop='^4'
bspc rule -a synergy            desktop='^9'
